name: sysdev_suretti
description: "A new Flutter project."
publish_to: 'none' 

version: 99.99.99+99

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.7
  cupertino_icons: ^1.0.6
  # flutter_blue_plus: ^1.32.8
  flutter_blue_plus: ^1.34.4
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  google_maps_flutter: ^2.10.0
  flutter_riverpod: ^2.5.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  uuid: ^4.4.2
  flutter_launcher_icons: ^0.14.1
  background_fetch: ^1.3.7
  beacon_broadcast: ^0.3.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  geolocator: ^8.2.1
  geocoding: ^3.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  animated_flip_counter: ^0.3.4
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.27
  path_provider: ^2.1.5
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.11

flutter:
  # assets:
  #   - .env
  fonts:
    - family: BIZ_UDPGothic
      fonts:
        - asset: assets\fonts\BIZ_UDPGothic\BIZUDPGothic-Regular.ttf
        - asset: assets\fonts\BIZ_UDPGothic\BIZUDPGothic-Bold.ttf
  uses-material-design: true

