# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  pull_request:
    branches: [ "main" ]

jobs:
   test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2.16.0
       with:
        flutter-version: '3.22.1'
        cache: true
        cache-key: flutter
        cache-path: ${{ runner.tool_cache }}/flutter
     - name: Install packages
       run: flutter pub get
     - name: Linter
       run: flutter analyze
     # - name: Test
     #   run: flutter test
