# This is a basic workflow to help you get started with Actions
name: CD Internal-Lane

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "internal-v*.*.*" # on every version tag will build a new android artifact example: v3.1.2+6
jobs:
  build:
    name: Build Artifacts and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: "3.22.1"

      - name: Decode android/neumodore_key.jks
        run: echo "${{ secrets.KEYSTORE_JKS_PROD }}" | base64 --decode > android/app/release.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties

      - name: Decode .env
        run: echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env

      - uses: olegtarasov/get-tag@v2.1.3 # that generate $GIT_TAG_NAME env
        id: tagName
        with:
          tagRegex: 'internal-v([0-9]+.[0-9]+.[0-9]+\+[0-9]+)' # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Replace YAML version with tag version
        run: |
          sed -i 's/99.99.99+99/'$GIT_TAG_NAME'/g' pubspec.yaml|
          echo "Tag used version:"$GIT_TAG_NAME
      - name: Pub Get Packages
        run: flutter pub get

      # - name: Build APPBUNDLE
      #   run: flutter build appbundle --release

      - name: Build APK
        run: flutter build apk --release --dart-define-from-file=.env

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          # artifacts: "build/app/outputs/bundle/release/*.aab"
          artifacts: "build/app/outputs/apk/release/*.apk"
          generateReleaseNotes: true
  
